<a href="https://colab.research.google.com/github/samiha-mahin/Data-Analysis/blob/main/Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("titanic.csv")

# **How big the data is?**

In [3]:
df.shape

(891, 12)

## **How does the data look like?**

In [4]:
df.head ()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df.sample(5) #better approach to see data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
628,629,0,3,"Bostandyeff, Mr. Guentcho",male,26.0,0,0,349224,7.8958,NaN,S
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C
114,115,0,3,"Attalah, Miss. Malake",female,17.0,0,0,2627,14.4583,NaN,C
767,768,0,3,"Mangan, Miss. Mary",female,30.5,0,0,364850,7.7500,NaN,Q
413,414,0,2,"Cunningham, Mr. Alfred Fleming",male,NaN,0,0,239853,0.0000,NaN,S

# **What are the data types in the column?**

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

# **Are there any missing values?**

In [7]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

# **How does the data look mathemetically?**

In [9]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

# **Are there any duplicate values ?**

In [10]:
df.duplicated().sum()

np.int64(0)

# **How is the correlation between cols?**

Correlation quantifies how two numbers change together. A positive correlation means they will increase or decrease together. A negative correlation means one increases as the other decreases. The closer the number is to 1 or -1, the stronger the linear relationship. Zero means no linear relationship.

In [12]:
# How is the correlation between cols?
df.corr(numeric_only=True)

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
PassengerId,1.000000,-0.005007,-0.035144,0.036847,-0.057527,-0.001652,0.012658
Survived,-0.005007,1.000000,-0.338481,-0.077221,-0.035322,0.081629,0.257307
Pclass,-0.035144,-0.338481,1.000000,-0.369226,0.083081,0.018443,-0.549500
Age,0.036847,-0.077221,-0.369226,1.000000,-0.308247,-0.189119,0.096067
SibSp,-0.057527,-0.035322,0.083081,-0.308247,1.000000,0.414838,0.159651
Parch,-0.001652,0.081629,0.018443,-0.189119,0.414838,1.000000,0.216225
Fare,0.012658,0.257307,-0.549500,0.096067,0.159651,0.216225,1.000000

# **Label Based selection** (.loc)



```
# This is using .loc[ ], so it's a label-based selection.

.loc[row_labels, column_labels]

: in rows → select all rows

: in columns → select all columns

newdf = df.loc[:,:] It creates a full copy of the original DataFrame (df) into a new DataFrame called newdf
```

In [14]:
newdf = df.loc[:,:]
newdf

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

# **Position-based indexing** (.iloc)



```
#  What is .iloc[]?
.iloc[] is for position-based indexing.

It uses integer positions, not label names.

What does 1:20, 1:4 mean?
1:20 → Rows from position 1 up to 19 (not including 20)

1:4 → Columns from position 1 up to 3 (not including 4)

So you're selecting:
Rows: 2nd to 20th row (index positions 1 to 19)

Columns: 2nd to 4th column
```

In [15]:
df.iloc[1:20, 1:4]

    Survived  Pclass                                               Name
1          1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2          1       3                             Heikkinen, Miss. Laina
3          1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4          0       3                           Allen, Mr. William Henry
5          0       3                                   Moran, Mr. James
6          0       1                            McCarthy, Mr. Timothy J
7          0       3                     Palsson, Master. Gosta Leonard
8          1       3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9          1       2                Nasser, Mrs. Nicholas (Adele Achem)
10         1       3                    Sandstrom, Miss. Marguerite Rut
11         1       1                           Bonnell, Miss. Elizabeth
12         0       3                     Saundercock, Mr. William Henry
13         0       3                        Andersson, Mr. Anders Johan
14         0       3               Vestrom, Miss. Hulda Amanda Adolfina
15         1       2                   Hewlett, Mrs. (Mary D Kingcome)
16         0       3                               Rice, Master. Eugene
17         1       2                       Williams, Mr. Charles Eugene
18         0       3  Vander Planke, Mrs. Julius (Emelia Maria Vande...
19         1       3                            Masselmani, Mrs. Fatima